-- Locations
INSERT IGNORE INTO `socially`.`locations` (`id`, `name`, `latitude`, `longitude`) VALUES
(14, 'Palas Mall', 47.15610000, 27.58660000),
(15, 'Teatrul National', 47.16330000, 27.58550000),
(16, 'Sala Polivalenta', 47.15650000, 27.58220000),
(17, 'Tiki Village', 47.17880000, 27.62550000),
(18, 'Gradina Botanica', 47.19120000, 27.55620000),
(19, 'Parcul Copou', 47.17720000, 27.56630000),
(20, 'Jassyro', 47.16420000, 27.58130000),
(21, 'Cuib', 47.16010000, 27.58430000),
(22, 'Mamma Mia', 47.16540000, 27.58000000),
(23, 'Legend Pub', 47.16480000, 27.58100000),
(24, 'Stadionul Emil Alexandrescu', 47.17890000, 27.55830000),
(25, 'Tucano Coffee', 47.15680000, 27.58550000);

-- Events
INSERT IGNORE INTO `socially`.`events` (`id`, `name`, `location_id`, `creator_user_id`, `desc`, `group_id`) VALUES
(20, 'Curs de dans #1', 23, 12, 'Invata pasi de salsa si bachata.', NULL),
(21, 'Yoga in aer liber #2', 17, 15, 'O ora de relaxare si meditatie in natura.', NULL),
(22, 'Degustare de vinuri #3', 21, 19, 'Descoperim arome noi alaturi de un somelier.', NULL),
(23, 'Festival de mancare #4', 17, 21, 'Cele mai bune preparate stradale te asteapta.', NULL),
(24, 'Expozitie de arta #5', 14, 20, 'Arta contemporana si socializare.', NULL),
(25, 'Festival de mancare #6', 18, 17, 'Cele mai bune preparate stradale te asteapta.', NULL),
(26, 'Seara de Karaoke #7', 17, 17, 'Canta piesele preferate alaturi de prieteni.', NULL),
(27, 'Curs de dans #8', 23, 10, 'Invata pasi de salsa si bachata.', NULL),
(28, 'Festival de mancare #9', 14, 16, 'Cele mai bune preparate stradale te asteapta.', NULL),
(29, 'Brunch de weekend #10', 14, 13, 'Clatite, oua benedict si mimosa nelimitat.', NULL),
(30, 'Seara de Board Games #11', 25, 24, 'Vino sa joci Catan, Dixit si multe altele.', NULL),
(31, 'Meci de fotbal #12', 22, 20, 'Vizionare pe ecran gigant a meciului saptamanii.', NULL),
(32, 'Stand-up Comedy #13', 17, 12, 'Portia ta de ras pentru acest weekend.', NULL),
(33, 'Expozitie de arta #14', 14, 18, 'Arta contemporana si socializare.', NULL),
(34, 'Concert de seara #15', 24, 15, 'Muzica live, atmosfera excelenta si bauturi reci.', NULL),
(35, 'Brunch de weekend #16', 20, 24, 'Clatite, oua benedict si mimosa nelimitat.', NULL),
(36, 'Yoga in aer liber #17', 19, 13, 'O ora de relaxare si meditatie in natura.', NULL),
(37, 'Degustare de vinuri #18', 22, 22, 'Descoperim arome noi alaturi de un somelier.', NULL),
(38, 'Brunch de weekend #19', 14, 20, 'Clatite, oua benedict si mimosa nelimitat.', NULL),
(39, 'Seara de Karaoke #20', 16, 20, 'Canta piesele preferate alaturi de prieteni.', NULL),
(40, 'Meci de fotbal #21', 23, 16, 'Vizionare pe ecran gigant a meciului saptamanii.', NULL),
(41, 'Degustare de vinuri #22', 20, 10, 'Descoperim arome noi alaturi de un somelier.', NULL),
(42, 'Petrecere cu DJ #23', 14, 14, 'Muzica electronica pana dimineata.', NULL),
(43, 'Targ de haine vintage #24', 15, 12, 'Gaseste piese unice la preturi mici.', NULL),
(44, 'Campionat de FIFA #25', 14, 19, 'Arata-ne cine e seful pe consola.', NULL),
(45, 'Degustare de vinuri #26', 14, 18, 'Descoperim arome noi alaturi de un somelier.', NULL),
(46, 'Seara de Board Games #27', 23, 17, 'Vino sa joci Catan, Dixit si multe altele.', NULL),
(47, 'Targ de haine vintage #28', 15, 12, 'Gaseste piese unice la preturi mici.', NULL),
(48, 'Festival de mancare #29', 17, 18, 'Cele mai bune preparate stradale te asteapta.', NULL),
(49, 'Seara de Karaoke #30', 24, 11, 'Canta piesele preferate alaturi de prieteni.', NULL),
(50, 'Campionat de FIFA #31', 14, 24, 'Arata-ne cine e seful pe consola.', NULL),
(51, 'Atelier de pictura #32', 15, 17, 'Relaxare prin arta si un pahar de vin.', NULL),
(52, 'Yoga in aer liber #33', 14, 10, 'O ora de relaxare si meditatie in natura.', NULL),
(53, 'Festival de mancare #34', 18, 11, 'Cele mai bune preparate stradale te asteapta.', NULL),
(54, 'Brunch de weekend #35', 14, 16, 'Clatite, oua benedict si mimosa nelimitat.', NULL),
(55, 'Curs de dans #36', 24, 20, 'Invata pasi de salsa si bachata.', NULL),
(56, 'Stand-up Comedy #37', 16, 11, 'Portia ta de ras pentru acest weekend.', NULL),
(57, 'Seara de Board Games #38', 20, 20, 'Vino sa joci Catan, Dixit si multe altele.', NULL),
(58, 'Expozitie de arta #39', 14, 24, 'Arta contemporana si socializare.', NULL),
(59, 'Stand-up Comedy #40', 14, 19, 'Portia ta de ras pentru acest weekend.', NULL),
(60, 'Curs de dans #41', 17, 10, 'Invata pasi de salsa si bachata.', NULL),
(61, 'Campionat de FIFA #42', 14, 10, 'Arata-ne cine e seful pe consola.', NULL),
(62, 'Concert de seara #43', 16, 12, 'Muzica live, atmosfera excelenta si bauturi reci.', NULL),
(63, 'Seara de Board Games #44', 14, 21, 'Vino sa joci Catan, Dixit si multe altele.', NULL),
(64, 'Seara de Board Games #45', 20, 19, 'Vino sa joci Catan, Dixit si multe altele.', NULL),
(65, 'Yoga in aer liber #46', 14, 19, 'O ora de relaxare si meditatie in natura.', NULL),
(66, 'Campionat de FIFA #47', 23, 20, 'Arata-ne cine e seful pe consola.', NULL),
(67, 'Festival de mancare #48', 19, 22, 'Cele mai bune preparate stradale te asteapta.', NULL),
(68, 'Seara de Board Games #49', 25, 10, 'Vino sa joci Catan, Dixit si multe altele.', NULL),
(69, 'Seara de Karaoke #50', 16, 21, 'Canta piesele preferate alaturi de prieteni.', NULL);

-- Location Filters
INSERT IGNORE INTO `socially`.`location_filters` (`location_id`, `filter_id`) VALUES
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'shopping mall' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'accessible parking' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'cinema' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'food court' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'museum' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'theater' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'opera house' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'art gallery' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'historic site' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'concert hall' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'arena' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'sports screening' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'large capacity' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'beach bar' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'lakeside' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'cocktail bar' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'dj' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'picnic area' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'nature reserve' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'pet friendly' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'open air venue' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'picnic area' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'nature reserve' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'pet friendly' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'open air venue' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'free wifi' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'laptop friendly' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'quiet hour' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'wine bar' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'vegetarian options' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'organic food' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = '24-hour venue' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'pizza' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'pool table' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'darts' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'craft beer bar' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'concert hall' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'arena' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'sports screening' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'large capacity' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'free wifi' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'laptop friendly' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'quiet hour' LIMIT 1));

-- Event Filters
INSERT IGNORE INTO `socially`.`event_filters` (`event_id`, `filter_id`) VALUES
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'nature reserve' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'quiet hour' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'wine bar' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'street food market' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'family room' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'museum' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'art gallery' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'historic site' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'quiet hour' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'street food market' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'family room' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(26, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(26, (SELECT id FROM `socially`.`filters` WHERE name = 'karaoke' LIMIT 1)),
(26, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(26, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(26, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(27, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(27, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(27, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(27, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(28, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(28, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(28, (SELECT id FROM `socially`.`filters` WHERE name = 'street food market' LIMIT 1)),
(28, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(28, (SELECT id FROM `socially`.`filters` WHERE name = 'family room' LIMIT 1)),
(28, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(29, (SELECT id FROM `socially`.`filters` WHERE name = 'brunch' LIMIT 1)),
(29, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(29, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(29, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(29, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(30, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(30, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(30, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(31, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(31, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(31, (SELECT id FROM `socially`.`filters` WHERE name = 'sports screening' LIMIT 1)),
(31, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(31, (SELECT id FROM `socially`.`filters` WHERE name = 'large capacity' LIMIT 1)),
(32, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(32, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(32, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(32, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(32, (SELECT id FROM `socially`.`filters` WHERE name = 'comedy club' LIMIT 1)),
(33, (SELECT id FROM `socially`.`filters` WHERE name = 'museum' LIMIT 1)),
(33, (SELECT id FROM `socially`.`filters` WHERE name = 'art gallery' LIMIT 1)),
(33, (SELECT id FROM `socially`.`filters` WHERE name = 'historic site' LIMIT 1)),
(33, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(33, (SELECT id FROM `socially`.`filters` WHERE name = 'quiet hour' LIMIT 1)),
(34, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(34, (SELECT id FROM `socially`.`filters` WHERE name = 'concert hall' LIMIT 1)),
(34, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(34, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(34, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(35, (SELECT id FROM `socially`.`filters` WHERE name = 'brunch' LIMIT 1)),
(35, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(35, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(35, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(35, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(36, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(36, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(36, (SELECT id FROM `socially`.`filters` WHERE name = 'nature reserve' LIMIT 1)),
(36, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(36, (SELECT id FROM `socially`.`filters` WHERE name = 'quiet hour' LIMIT 1)),
(37, (SELECT id FROM `socially`.`filters` WHERE name = 'wine bar' LIMIT 1)),
(37, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(37, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(38, (SELECT id FROM `socially`.`filters` WHERE name = 'brunch' LIMIT 1)),
(38, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(38, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(38, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(38, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(39, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(39, (SELECT id FROM `socially`.`filters` WHERE name = 'karaoke' LIMIT 1)),
(39, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(39, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(39, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(40, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(40, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(40, (SELECT id FROM `socially`.`filters` WHERE name = 'sports screening' LIMIT 1)),
(40, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(40, (SELECT id FROM `socially`.`filters` WHERE name = 'large capacity' LIMIT 1)),
(41, (SELECT id FROM `socially`.`filters` WHERE name = 'wine bar' LIMIT 1)),
(41, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(41, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(42, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(42, (SELECT id FROM `socially`.`filters` WHERE name = 'cocktail bar' LIMIT 1)),
(42, (SELECT id FROM `socially`.`filters` WHERE name = 'late night venue' LIMIT 1)),
(42, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(42, (SELECT id FROM `socially`.`filters` WHERE name = 'dj' LIMIT 1)),
(43, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(43, (SELECT id FROM `socially`.`filters` WHERE name = 'family room' LIMIT 1)),
(43, (SELECT id FROM `socially`.`filters` WHERE name = 'shopping mall' LIMIT 1)),
(43, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(44, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(44, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(44, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(44, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(45, (SELECT id FROM `socially`.`filters` WHERE name = 'wine bar' LIMIT 1)),
(45, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(45, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(46, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(46, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(46, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(47, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(47, (SELECT id FROM `socially`.`filters` WHERE name = 'family room' LIMIT 1)),
(47, (SELECT id FROM `socially`.`filters` WHERE name = 'shopping mall' LIMIT 1)),
(47, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(48, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(48, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(48, (SELECT id FROM `socially`.`filters` WHERE name = 'street food market' LIMIT 1)),
(48, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(48, (SELECT id FROM `socially`.`filters` WHERE name = 'family room' LIMIT 1)),
(48, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(49, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(49, (SELECT id FROM `socially`.`filters` WHERE name = 'karaoke' LIMIT 1)),
(49, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(49, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(49, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(50, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(50, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(50, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(50, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(51, (SELECT id FROM `socially`.`filters` WHERE name = 'museum' LIMIT 1)),
(51, (SELECT id FROM `socially`.`filters` WHERE name = 'art gallery' LIMIT 1)),
(51, (SELECT id FROM `socially`.`filters` WHERE name = 'historic site' LIMIT 1)),
(51, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(51, (SELECT id FROM `socially`.`filters` WHERE name = 'quiet hour' LIMIT 1)),
(52, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(52, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(52, (SELECT id FROM `socially`.`filters` WHERE name = 'nature reserve' LIMIT 1)),
(52, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(52, (SELECT id FROM `socially`.`filters` WHERE name = 'quiet hour' LIMIT 1)),
(53, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(53, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(53, (SELECT id FROM `socially`.`filters` WHERE name = 'street food market' LIMIT 1)),
(53, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(53, (SELECT id FROM `socially`.`filters` WHERE name = 'family room' LIMIT 1)),
(53, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(54, (SELECT id FROM `socially`.`filters` WHERE name = 'brunch' LIMIT 1)),
(54, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(54, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(54, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(54, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(55, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(55, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(55, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(55, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(56, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(56, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(56, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(56, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(56, (SELECT id FROM `socially`.`filters` WHERE name = 'comedy club' LIMIT 1)),
(57, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(57, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(57, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(58, (SELECT id FROM `socially`.`filters` WHERE name = 'museum' LIMIT 1)),
(58, (SELECT id FROM `socially`.`filters` WHERE name = 'art gallery' LIMIT 1)),
(58, (SELECT id FROM `socially`.`filters` WHERE name = 'historic site' LIMIT 1)),
(58, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(58, (SELECT id FROM `socially`.`filters` WHERE name = 'quiet hour' LIMIT 1)),
(59, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(59, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(59, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(59, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(59, (SELECT id FROM `socially`.`filters` WHERE name = 'comedy club' LIMIT 1)),
(60, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(60, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(60, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(60, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(61, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(61, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(61, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(61, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(62, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(62, (SELECT id FROM `socially`.`filters` WHERE name = 'concert hall' LIMIT 1)),
(62, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(62, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(62, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(63, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(63, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(63, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(64, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(64, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(64, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(65, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(65, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(65, (SELECT id FROM `socially`.`filters` WHERE name = 'nature reserve' LIMIT 1)),
(65, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(65, (SELECT id FROM `socially`.`filters` WHERE name = 'quiet hour' LIMIT 1)),
(66, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(66, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(66, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(66, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(67, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(67, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(67, (SELECT id FROM `socially`.`filters` WHERE name = 'street food market' LIMIT 1)),
(67, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(67, (SELECT id FROM `socially`.`filters` WHERE name = 'family room' LIMIT 1)),
(67, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(68, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(68, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(68, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(69, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(69, (SELECT id FROM `socially`.`filters` WHERE name = 'karaoke' LIMIT 1)),
(69, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(69, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(69, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1));

