SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM `socially`.`event_filters`;
DELETE FROM `socially`.`location_filters`;
DELETE FROM `socially`.`events`;
DELETE FROM `socially`.`locations`;
SET FOREIGN_KEY_CHECKS = 1;

-- NO ALTERATIONS TO FILTERS TABLE. USING EXACT DB MATCHES.

-- Locations
INSERT INTO `socially`.`locations` (`id`, `name`, `latitude`, `longitude`) VALUES
(10, 'Viper Club', 47.15580000, 27.60440000),
(11, 'Time Out', 47.17250000, 27.57500000),
(12, 'Zona de Agrement Ciric', 47.17850000, 27.62580000),
(13, 'Cafeneaua Acaju', 47.16450000, 27.58620000),
(14, 'Palas Mall', 47.15610000, 27.58660000),
(15, 'Teatrul National', 47.16330000, 27.58550000),
(16, 'Sala Polivalenta', 47.15650000, 27.58220000),
(17, 'Tiki Village', 47.17880000, 27.62550000),
(18, 'Gradina Botanica', 47.19120000, 27.55620000),
(19, 'Parcul Copou', 47.17720000, 27.56630000),
(20, 'Jassyro', 47.16420000, 27.58130000),
(21, 'Cuib', 47.16010000, 27.58430000),
(22, 'Mamma Mia', 47.16540000, 27.58000000),
(23, 'Legend Pub', 47.16480000, 27.58100000),
(24, 'Stadionul Emil Alexandrescu', 47.17890000, 27.55830000),
(25, 'Tucano Coffee', 47.15680000, 27.58550000);

-- Events
INSERT INTO `socially`.`events` (`id`, `name`, `location_id`, `creator_user_id`, `desc`, `group_id`, `date`) VALUES
(10, 'Dimineata cu specialty coffee', 13, 24, 'Testam cele mai noi arome de cafea aduse direct din Etiopia.', NULL, '2026-06-01 01:40:47'),
(11, 'Pauza de espresso si lectura', 25, 16, 'Te relaxezi cu un espresso dublu si o carte buna din biblioteca cafenelei.', NULL, '2026-06-12 08:40:47'),
(12, 'Degustare de deserturi cu cafea', 20, 22, 'Asociem prajiturile vegane cu un latte art desavarsit.', NULL, '2026-05-31 19:40:47'),
(13, 'Networking la o cafea fierbinte', 25, 12, 'Intalnire cu tineri antreprenori la cafeneaua din colt.', NULL, '2026-06-15 23:40:47'),
(14, 'Seara de Board Games si Cappuccino', 20, 13, 'Jucam Catan, dar cu super multa cofeina.', NULL, '2026-06-03 19:40:47'),
(15, 'Cina Romantica in doi', 21, 24, 'Atmosfera de vis, vin rosu si meniu a la carte.', NULL, '2026-05-28 02:40:47'),
(16, 'Seara de Sushi All You Can Eat', 21, 13, 'Maki si Nigiri cat poti sa mananci in 2 ore.', NULL, '2026-06-11 12:40:47'),
(17, 'Degustare meniu vegan', 21, 12, 'Bucatarul nostru a creat cele mai tari preparate vegane.', NULL, '2026-06-08 07:40:47'),
(18, 'Brunch de weekend tarziu', 21, 12, 'Clatite americane si avocado toast pentru toata familia.', NULL, '2026-06-06 04:40:47'),
(19, 'Experienta culinara Italiana', 21, 10, 'Paste proaspete si muzica usoara pe fundal.', NULL, '2026-06-16 06:40:47'),
(20, 'Pizza Festival', 14, 11, 'Incerci 10 feluri de pizza felie cu felie.', NULL, '2026-05-29 17:40:47'),
(21, 'Burger Challenge XXL', 22, 17, 'Mananca cel mai mare burger in 10 minute si e din partea casei.', NULL, '2026-06-09 12:40:47'),
(22, 'Shaorma la 2 dimineata', 22, 21, 'Te asteptam dupa petrecere cu o masa copioasa.', NULL, '2026-06-13 17:40:47'),
(23, 'Oferta de pranz Meniul Zilei', 14, 18, 'Snitel cu cartofi prajiti si multa voie buna.', NULL, '2026-06-02 06:40:47'),
(24, 'Tacos si sos picant', 14, 10, 'Cat de iute poti sa mananci? Hai la provocare.', NULL, '2026-06-17 08:40:47'),
(25, 'Concert Rock Acustic', 11, 14, 'Piese clasice cantate doar la chitara de un artist local.', NULL, '2026-06-01 10:40:47'),
(26, 'Seara de Quiz Pub', 23, 24, 'Fa-ti echipa si vino sa castigi un rand de beri.', NULL, '2026-06-02 02:40:47'),
(27, 'Campionat de Darts la Halba', 11, 23, 'O seara relaxanta aruncand sageti dupa o bere artizanala.', NULL, '2026-05-28 00:40:47'),
(28, 'Tribut formatiei Queen', 10, 13, 'Trupa de cover-uri reface energia unui concert legendar.', NULL, '2026-06-18 17:40:47'),
(29, 'Karaoke Night Fara Rusine', 11, 17, 'Nimeni nu te judeca la karaoke cand esti cu prietenii.', NULL, '2026-06-13 08:40:47'),
(30, 'Petrecere Retro Anii 90', 17, 24, 'Dansezi pana pici pe hiturile copilariei.', NULL, '2026-05-31 09:40:47'),
(31, 'Techno Vibes pe plaja', 17, 19, 'DJ-ul invitat direct din Berlin ne tine treji pana dimineata.', NULL, '2026-05-28 05:40:47'),
(32, 'Cocktail Masterclass si Party', 17, 12, 'Invata sa mixezi bauturi si apoi distreaza-te.', NULL, '2026-06-12 06:40:47'),
(33, 'Neon Glow Party', 17, 14, 'Pune hainele care stralucesc si arata-ne miscarile tale.', NULL, '2026-06-14 17:40:47'),
(34, 'Latino Night Fiesta', 17, 16, 'Bachata, salsa si shot-uri de tequila.', NULL, '2026-06-12 14:40:47'),
(35, 'Piesa de teatru Moliere', 15, 11, 'Comedie clasica in 3 acte cu o distributie de exceptie.', NULL, '2026-06-11 20:40:47'),
(36, 'Expozitie de arta abstracta', 15, 19, 'Vernisajul aduce tineri artisti si un pahar de sampanie.', NULL, '2026-05-27 23:40:47'),
(37, 'Tur ghidat in culise', 15, 23, 'Afla istoria cladirii si povestile ascunse din spatele scenei.', NULL, '2026-06-17 12:40:47'),
(38, 'Noaptea Muzeelor in avans', 15, 11, 'Vizitare nocturna la o expozitie de arheologie rara.', NULL, '2026-05-27 10:40:47'),
(39, 'Monolog Dramatic - Actorul X', 15, 16, 'Un one-man show ce te va tine in suspans.', NULL, '2026-06-08 19:40:47'),
(40, 'Yoga pe iarba in zori', 12, 17, 'Exercitii de stretching si meditatie in mijlocul naturii.', NULL, '2026-06-20 21:40:47'),
(41, 'Picnic comunitar de Duminica', 18, 16, 'Fiecare aduce ceva bun si impartim la umbra copacilor.', NULL, '2026-06-03 00:40:47'),
(42, 'Intalnirea Catzelusilor Jucausi', 12, 19, 'Adu-ti cainele la o joaca generala in parcul mare.', NULL, '2026-06-10 05:40:47'),
(43, 'Turul plantelor exotice', 18, 18, 'Ghid botanic despre florile rare din gradina.', NULL, '2026-06-06 23:40:47'),
(44, 'Lectura in hamac', 19, 21, 'Aducem noi hamacele, tu vino cu cartea preferata.', NULL, '2026-06-09 09:40:47'),
(45, 'Maratonul reducerilor de iarna', 14, 16, '3 zile de preturi taiate direct in mall.', NULL, '2026-06-20 19:40:47'),
(46, 'Vizionare in avanpremiera la Cinema', 14, 12, 'Esti primul care vede blockbusterul mult asteptat.', NULL, '2026-05-25 22:40:47'),
(47, 'Parada de Moda Toamna', 14, 18, 'Noile colectii prezentate direct pe culoarul principal.', NULL, '2026-05-26 17:40:47'),
(48, 'Turneu de FIFA 26 in atrium', 14, 17, 'Competitie mare de e-sports, castigatorul primeste un PS6.', NULL, '2026-06-05 05:40:47'),
(49, 'Atelier de pictat globuri', 14, 20, 'Activitate creativa pentru copii cu parintii lor.', NULL, '2026-05-30 02:40:47'),
(50, 'Derby-ul Orasului la Fotbal', 16, 19, 'Emotie si adrenalina pura pe stadion.', NULL, '2026-05-29 11:40:47'),
(51, 'Meci International de Baschet', 24, 12, 'Nationala revine acasa pentru calificarile europene.', NULL, '2026-06-06 02:40:47'),
(52, 'Gala de Box Profesionist', 24, 23, 'Luptatori de top si o atmosfera incendiara.', NULL, '2026-06-01 04:40:47'),
(53, 'Antrenament public de echipa', 16, 12, 'Vino sa iei autografe si sa vezi baietii la antrenament.', NULL, '2026-05-25 08:40:47'),
(54, 'Vizionare Meci Champions League', 16, 21, 'Proiectam finala pe cel mai mare ecran disponibil.', NULL, '2026-06-07 09:40:47');

-- Location Filters
INSERT INTO `socially`.`location_filters` (`location_id`, `filter_id`) VALUES
(10, (SELECT id FROM `socially`.`filters` WHERE name = 'pool table' LIMIT 1)),
(10, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(10, (SELECT id FROM `socially`.`filters` WHERE name = 'craft beer' LIMIT 1)),
(10, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(10, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(10, (SELECT id FROM `socially`.`filters` WHERE name = 'darts' LIMIT 1)),
(10, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(11, (SELECT id FROM `socially`.`filters` WHERE name = 'pool table' LIMIT 1)),
(11, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(11, (SELECT id FROM `socially`.`filters` WHERE name = 'craft beer' LIMIT 1)),
(11, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(11, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(11, (SELECT id FROM `socially`.`filters` WHERE name = 'darts' LIMIT 1)),
(11, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(12, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoors' LIMIT 1)),
(12, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(12, (SELECT id FROM `socially`.`filters` WHERE name = 'pet friendly' LIMIT 1)),
(12, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(12, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(12, (SELECT id FROM `socially`.`filters` WHERE name = 'picnic area' LIMIT 1)),
(12, (SELECT id FROM `socially`.`filters` WHERE name = 'nature reserve' LIMIT 1)),
(13, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(13, (SELECT id FROM `socially`.`filters` WHERE name = 'free wifi' LIMIT 1)),
(13, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(13, (SELECT id FROM `socially`.`filters` WHERE name = 'wellness' LIMIT 1)),
(13, (SELECT id FROM `socially`.`filters` WHERE name = 'coworking space' LIMIT 1)),
(13, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'food court' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'accessible parking' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'cinema' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'shopping mall' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'family friendly' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'museum' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'historic site' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'art gallery' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'theatre' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'live sports screening' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'concert hall' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'festival' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'cocktail bar' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'lakeside' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'beach bar' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'dj' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoors' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'pet friendly' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'picnic area' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'nature reserve' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoors' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'pet friendly' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'picnic area' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'nature reserve' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'free wifi' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'wellness' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'coworking space' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'organic food' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'vegetarian options' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'wine bar' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'pizza' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'pool table' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'craft beer' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'darts' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'live sports screening' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'concert hall' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'festival' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'free wifi' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'wellness' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'coworking space' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1));

-- Event Filters
INSERT INTO `socially`.`event_filters` (`event_id`, `filter_id`) VALUES
(10, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(10, (SELECT id FROM `socially`.`filters` WHERE name = 'coworking space' LIMIT 1)),
(10, (SELECT id FROM `socially`.`filters` WHERE name = 'free wifi' LIMIT 1)),
(10, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(11, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(11, (SELECT id FROM `socially`.`filters` WHERE name = 'coworking space' LIMIT 1)),
(11, (SELECT id FROM `socially`.`filters` WHERE name = 'free wifi' LIMIT 1)),
(11, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(12, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(12, (SELECT id FROM `socially`.`filters` WHERE name = 'coworking space' LIMIT 1)),
(12, (SELECT id FROM `socially`.`filters` WHERE name = 'free wifi' LIMIT 1)),
(12, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(13, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(13, (SELECT id FROM `socially`.`filters` WHERE name = 'coworking space' LIMIT 1)),
(13, (SELECT id FROM `socially`.`filters` WHERE name = 'free wifi' LIMIT 1)),
(13, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'cafe' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'coworking space' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'free wifi' LIMIT 1)),
(14, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'wine bar' LIMIT 1)),
(15, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'wine bar' LIMIT 1)),
(16, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'wine bar' LIMIT 1)),
(17, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'wine bar' LIMIT 1)),
(18, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'vegan options' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'wine bar' LIMIT 1)),
(19, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = '24-hour venue' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(20, (SELECT id FROM `socially`.`filters` WHERE name = 'pizza' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = '24-hour venue' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(21, (SELECT id FROM `socially`.`filters` WHERE name = 'pizza' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = '24-hour venue' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(22, (SELECT id FROM `socially`.`filters` WHERE name = 'pizza' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = '24-hour venue' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(23, (SELECT id FROM `socially`.`filters` WHERE name = 'pizza' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = '24-hour venue' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'fast food' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'burger' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'restaurant' LIMIT 1)),
(24, (SELECT id FROM `socially`.`filters` WHERE name = 'pizza' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'craft beer' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'darts' LIMIT 1)),
(25, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(26, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(26, (SELECT id FROM `socially`.`filters` WHERE name = 'craft beer' LIMIT 1)),
(26, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(26, (SELECT id FROM `socially`.`filters` WHERE name = 'darts' LIMIT 1)),
(26, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(27, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(27, (SELECT id FROM `socially`.`filters` WHERE name = 'craft beer' LIMIT 1)),
(27, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(27, (SELECT id FROM `socially`.`filters` WHERE name = 'darts' LIMIT 1)),
(27, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(28, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(28, (SELECT id FROM `socially`.`filters` WHERE name = 'craft beer' LIMIT 1)),
(28, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(28, (SELECT id FROM `socially`.`filters` WHERE name = 'darts' LIMIT 1)),
(28, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(29, (SELECT id FROM `socially`.`filters` WHERE name = 'board games' LIMIT 1)),
(29, (SELECT id FROM `socially`.`filters` WHERE name = 'craft beer' LIMIT 1)),
(29, (SELECT id FROM `socially`.`filters` WHERE name = 'pub' LIMIT 1)),
(29, (SELECT id FROM `socially`.`filters` WHERE name = 'darts' LIMIT 1)),
(29, (SELECT id FROM `socially`.`filters` WHERE name = 'live music' LIMIT 1)),
(30, (SELECT id FROM `socially`.`filters` WHERE name = 'cocktail bar' LIMIT 1)),
(30, (SELECT id FROM `socially`.`filters` WHERE name = 'nightlife' LIMIT 1)),
(30, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(30, (SELECT id FROM `socially`.`filters` WHERE name = 'dj' LIMIT 1)),
(30, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(31, (SELECT id FROM `socially`.`filters` WHERE name = 'cocktail bar' LIMIT 1)),
(31, (SELECT id FROM `socially`.`filters` WHERE name = 'nightlife' LIMIT 1)),
(31, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(31, (SELECT id FROM `socially`.`filters` WHERE name = 'dj' LIMIT 1)),
(31, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(32, (SELECT id FROM `socially`.`filters` WHERE name = 'cocktail bar' LIMIT 1)),
(32, (SELECT id FROM `socially`.`filters` WHERE name = 'nightlife' LIMIT 1)),
(32, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(32, (SELECT id FROM `socially`.`filters` WHERE name = 'dj' LIMIT 1)),
(32, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(33, (SELECT id FROM `socially`.`filters` WHERE name = 'cocktail bar' LIMIT 1)),
(33, (SELECT id FROM `socially`.`filters` WHERE name = 'nightlife' LIMIT 1)),
(33, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(33, (SELECT id FROM `socially`.`filters` WHERE name = 'dj' LIMIT 1)),
(33, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(34, (SELECT id FROM `socially`.`filters` WHERE name = 'cocktail bar' LIMIT 1)),
(34, (SELECT id FROM `socially`.`filters` WHERE name = 'nightlife' LIMIT 1)),
(34, (SELECT id FROM `socially`.`filters` WHERE name = 'nightclub' LIMIT 1)),
(34, (SELECT id FROM `socially`.`filters` WHERE name = 'dj' LIMIT 1)),
(34, (SELECT id FROM `socially`.`filters` WHERE name = 'bar' LIMIT 1)),
(35, (SELECT id FROM `socially`.`filters` WHERE name = 'wellness' LIMIT 1)),
(35, (SELECT id FROM `socially`.`filters` WHERE name = 'museum' LIMIT 1)),
(35, (SELECT id FROM `socially`.`filters` WHERE name = 'historic site' LIMIT 1)),
(35, (SELECT id FROM `socially`.`filters` WHERE name = 'art gallery' LIMIT 1)),
(35, (SELECT id FROM `socially`.`filters` WHERE name = 'theatre' LIMIT 1)),
(36, (SELECT id FROM `socially`.`filters` WHERE name = 'wellness' LIMIT 1)),
(36, (SELECT id FROM `socially`.`filters` WHERE name = 'museum' LIMIT 1)),
(36, (SELECT id FROM `socially`.`filters` WHERE name = 'historic site' LIMIT 1)),
(36, (SELECT id FROM `socially`.`filters` WHERE name = 'art gallery' LIMIT 1)),
(36, (SELECT id FROM `socially`.`filters` WHERE name = 'theatre' LIMIT 1)),
(37, (SELECT id FROM `socially`.`filters` WHERE name = 'wellness' LIMIT 1)),
(37, (SELECT id FROM `socially`.`filters` WHERE name = 'museum' LIMIT 1)),
(37, (SELECT id FROM `socially`.`filters` WHERE name = 'historic site' LIMIT 1)),
(37, (SELECT id FROM `socially`.`filters` WHERE name = 'art gallery' LIMIT 1)),
(37, (SELECT id FROM `socially`.`filters` WHERE name = 'theatre' LIMIT 1)),
(38, (SELECT id FROM `socially`.`filters` WHERE name = 'wellness' LIMIT 1)),
(38, (SELECT id FROM `socially`.`filters` WHERE name = 'museum' LIMIT 1)),
(38, (SELECT id FROM `socially`.`filters` WHERE name = 'historic site' LIMIT 1)),
(38, (SELECT id FROM `socially`.`filters` WHERE name = 'art gallery' LIMIT 1)),
(38, (SELECT id FROM `socially`.`filters` WHERE name = 'theatre' LIMIT 1)),
(39, (SELECT id FROM `socially`.`filters` WHERE name = 'wellness' LIMIT 1)),
(39, (SELECT id FROM `socially`.`filters` WHERE name = 'museum' LIMIT 1)),
(39, (SELECT id FROM `socially`.`filters` WHERE name = 'historic site' LIMIT 1)),
(39, (SELECT id FROM `socially`.`filters` WHERE name = 'art gallery' LIMIT 1)),
(39, (SELECT id FROM `socially`.`filters` WHERE name = 'theatre' LIMIT 1)),
(40, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(40, (SELECT id FROM `socially`.`filters` WHERE name = 'pet friendly' LIMIT 1)),
(40, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(40, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(40, (SELECT id FROM `socially`.`filters` WHERE name = 'picnic area' LIMIT 1)),
(41, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(41, (SELECT id FROM `socially`.`filters` WHERE name = 'pet friendly' LIMIT 1)),
(41, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(41, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(41, (SELECT id FROM `socially`.`filters` WHERE name = 'picnic area' LIMIT 1)),
(42, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(42, (SELECT id FROM `socially`.`filters` WHERE name = 'pet friendly' LIMIT 1)),
(42, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(42, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(42, (SELECT id FROM `socially`.`filters` WHERE name = 'picnic area' LIMIT 1)),
(43, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(43, (SELECT id FROM `socially`.`filters` WHERE name = 'pet friendly' LIMIT 1)),
(43, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(43, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(43, (SELECT id FROM `socially`.`filters` WHERE name = 'picnic area' LIMIT 1)),
(44, (SELECT id FROM `socially`.`filters` WHERE name = 'park setting' LIMIT 1)),
(44, (SELECT id FROM `socially`.`filters` WHERE name = 'pet friendly' LIMIT 1)),
(44, (SELECT id FROM `socially`.`filters` WHERE name = 'botanical garden' LIMIT 1)),
(44, (SELECT id FROM `socially`.`filters` WHERE name = 'outdoor seating' LIMIT 1)),
(44, (SELECT id FROM `socially`.`filters` WHERE name = 'picnic area' LIMIT 1)),
(45, (SELECT id FROM `socially`.`filters` WHERE name = 'cinema' LIMIT 1)),
(45, (SELECT id FROM `socially`.`filters` WHERE name = 'shopping mall' LIMIT 1)),
(45, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(45, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(46, (SELECT id FROM `socially`.`filters` WHERE name = 'cinema' LIMIT 1)),
(46, (SELECT id FROM `socially`.`filters` WHERE name = 'shopping mall' LIMIT 1)),
(46, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(46, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(47, (SELECT id FROM `socially`.`filters` WHERE name = 'cinema' LIMIT 1)),
(47, (SELECT id FROM `socially`.`filters` WHERE name = 'shopping mall' LIMIT 1)),
(47, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(47, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(48, (SELECT id FROM `socially`.`filters` WHERE name = 'cinema' LIMIT 1)),
(48, (SELECT id FROM `socially`.`filters` WHERE name = 'shopping mall' LIMIT 1)),
(48, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(48, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(49, (SELECT id FROM `socially`.`filters` WHERE name = 'cinema' LIMIT 1)),
(49, (SELECT id FROM `socially`.`filters` WHERE name = 'shopping mall' LIMIT 1)),
(49, (SELECT id FROM `socially`.`filters` WHERE name = 'wheelchair accessible' LIMIT 1)),
(49, (SELECT id FROM `socially`.`filters` WHERE name = 'indoors' LIMIT 1)),
(50, (SELECT id FROM `socially`.`filters` WHERE name = 'festival' LIMIT 1)),
(50, (SELECT id FROM `socially`.`filters` WHERE name = 'live sports screening' LIMIT 1)),
(50, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(50, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(51, (SELECT id FROM `socially`.`filters` WHERE name = 'festival' LIMIT 1)),
(51, (SELECT id FROM `socially`.`filters` WHERE name = 'live sports screening' LIMIT 1)),
(51, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(51, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(52, (SELECT id FROM `socially`.`filters` WHERE name = 'festival' LIMIT 1)),
(52, (SELECT id FROM `socially`.`filters` WHERE name = 'live sports screening' LIMIT 1)),
(52, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(52, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(53, (SELECT id FROM `socially`.`filters` WHERE name = 'festival' LIMIT 1)),
(53, (SELECT id FROM `socially`.`filters` WHERE name = 'live sports screening' LIMIT 1)),
(53, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(53, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(54, (SELECT id FROM `socially`.`filters` WHERE name = 'festival' LIMIT 1)),
(54, (SELECT id FROM `socially`.`filters` WHERE name = 'live sports screening' LIMIT 1)),
(54, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1)),
(54, (SELECT id FROM `socially`.`filters` WHERE name = 'stadium' LIMIT 1));


