INSERT IGNORE INTO `socially`.`filters` (`name`) VALUES 
('24-hour venue'),
('accessible entrance'),
('accessible parking'),
('accessible toilets'),
('adult only'),
('adventure park'),
('air conditioning'),
('alcohol'),
('american cuisine'),
('amusement park'),
('aquarium'),
('arcade'),
('art & culture'),
('art gallery'),
('asian cuisine'),
('athletics track'),
('axe throwing venue'),
('baby changing facilities'),
('bakery'),
('bar'),
('basement venue'),
('basketball court'),
('bbq facilities'),
('beach'),
('beach bar'),
('beachfront'),
('beer'),
('beer garden'),
('bicycle parking'),
('billiards'),
('bingo hall'),
('bistro'),
('board games'),
('boat hire'),
('book reading'),
('bookstore'),
('botanical garden'),
('bouldering gym'),
('boutique'),
('bowling'),
('breakfast & brunch'),
('bubble tea shop'),
('buffet'),
('burger'),
('cable car'),
('cafe'),
('campground'),
('car parking'),
('card payment accepted'),
('caribbean cuisine'),
('cashless venue'),
('casino'),
('castle'),
('children''s menu'),
('chinese cuisine'),
('cigar lounge'),
('cinema'),
('climbing wall'),
('cocktail bar'),
('cocktails'),
('coffee'),
('coffee shop'),
('comedy club'),
('competition'),
('concert hall'),
('contactless payment'),
('cooking school'),
('courtyard'),
('courtyard garden'),
('coworking space'),
('craft beer'),
('creperie'),
('dairy-free options'),
('dance studio'),
('dancing'),
('darts'),
('delivery'),
('dessert shop'),
('disabled parking bay'),
('distillery'),
('distillery tour'),
('dive bar'),
('dj'),
('dog park'),
('drinks'),
('drive-through'),
('early morning venue'),
('education'),
('escape room'),
('exhibition'),
('family friendly'),
('farmers market'),
('fast food'),
('festival'),
('food'),
('food court'),
('food truck'),
('football pitch'),
('forest setting'),
('free parking'),
('free wifi'),
('french cuisine'),
('games'),
('gaming lounge'),
('gluten-free options'),
('go-kart track'),
('golf'),
('greek cuisine'),
('gym'),
('halal certified'),
('hiking trail'),
('historic site'),
('hookah lounge'),
('hotel bar'),
('ice cream'),
('ice skating'),
('indian cuisine'),
('indoors'),
('island location'),
('italian cuisine'),
('japanese cuisine'),
('juice bar'),
('karaoke'),
('kebab'),
('kid friendly'),
('kids play area'),
('korean cuisine'),
('kosher certified'),
('lakeside'),
('language exchange'),
('laser tag venue'),
('lebanese cuisine'),
('live entertainment'),
('live music'),
('live sports screening'),
('lounge'),
('marina'),
('martial arts'),
('mediterranean cuisine'),
('mexican cuisine'),
('middle eastern cuisine'),
('mini golf'),
('museum'),
('music'),
('nature reserve'),
('networking'),
('nightclub'),
('nightlife'),
('nut-free options'),
('observatory'),
('open mic'),
('opera house'),
('organic food'),
('outdoor cinema'),
('outdoor seating'),
('outdoors'),
('paintball venue'),
('palace'),
('park'),
('park setting'),
('parking'),
('parking available'),
('party'),
('pet friendly'),
('photography'),
('picnic area'),
('pizza'),
('planetarium'),
('pool table'),
('pop-up event'),
('pub'),
('public square'),
('quiz night'),
('ramen'),
('restaurant'),
('riverside'),
('roller skating'),
('romance'),
('romanian cuisine'),
('rooftop'),
('rugby pitch'),
('seafood'),
('shopping'),
('shopping mall'),
('skatepark'),
('smoking area'),
('social dancing'),
('socializing'),
('spa'),
('spanish cuisine'),
('speakeasy'),
('sports'),
('sports bar'),
('sports hall'),
('stadium'),
('stand-up comedy'),
('steakhouse'),
('street food'),
('supermarket'),
('swimming pool'),
('takeaway'),
('tapas'),
('tasting event'),
('tavern'),
('tea'),
('tea room'),
('tennis court'),
('terrace'),
('thai cuisine'),
('theatre'),
('theme park'),
('thrift store'),
('trampoline park'),
('urban setting'),
('valet parking'),
('vegan options'),
('vegetarian options'),
('vietnamese cuisine'),
('viewpoint'),
('virtual reality center'),
('volleyball court'),
('volunteering'),
('vr gaming'),
('water park'),
('water sports'),
('waterfront'),
('wellness'),
('wheelchair accessible'),
('wine'),
('wine bar'),
('winery'),
('winery tour'),
('workshop'),
('yoga studio'),
('zero waste venue'),
('zipline'),
('zoo');
