name: Deploy Database Migrations

on:
  push:
    branches:
      - main 

jobs:
  run-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Tragem codul din repo
        uses: actions/checkout@v4

      - name: Rulam Flyway prin imagine Docker
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/migrations:/flyway/sql \
          flyway/flyway:latest \
          -url="${{ secrets.TIDB_URL }}" \
          migrate
